#!/opt/conda/bin/python

import os

print("Updating BioSimSpace...")

print("  -- [u] BioSimSpace")
os.chdir("/home/biosimspace/python")
os.system("git pull")
os.system("BSS_SKIP_INSTALL=1 /opt/conda/bin/python setup.py install >> /dev/null 2>&1")

print("\nEverything updated :-)")
