#!/opt/conda/bin/python

import os

print("Updating BioSimSpace...")

result = os.system("conda update -c rdkit -c conda-forge -c omnia -c michellab/label/dev biosimspace")

if result == 0:
    print("\n\nEverything updated :-)")
else:
    print("\n\nSomething went wrong?")
