######################################################################
# BioSimSpace: Making biomolecular simulation a breeze!
#
# Copyright: 2017-2023
#
# Authors: Lester Hedges <lester.hedges@gmail.com>
#
# BioSimSpace is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BioSimSpace is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with BioSimSpace. If not, see <http://www.gnu.org/licenses/>.
#####################################################################
""" 
Utilities.
"""

# A set of protein residues. Taken from MDAnalysis.
_prot_res = {
    # CHARMM top_all27_prot_lipid.rtf
    "ALA",
    "ARG",
    "ASN",
    "ASP",
    "CYS",
    "GLN",
    "GLU",
    "GLY",
    "HSD",
    "HSE",
    "HSP",
    "ILE",
    "LEU",
    "LYS",
    "MET",
    "PHE",
    "PRO",
    "SER",
    "THR",
    "TRP",
    "TYR",
    "VAL",
    "ALAD",
    ## 'CHO','EAM', # -- special formyl and ethanolamine termini of gramicidin
    # PDB
    "HIS",
    "MSE",
    # from Gromacs 4.5.3 oplsaa.ff/aminoacids.rtp
    "ARGN",
    "ASPH",
    "CYS2",
    "CYSH",
    "QLN",
    "PGLU",
    "GLUH",
    "HIS1",
    "HISD",
    "HISE",
    "HISH",
    "LYSH",
    # from Gromacs 4.5.3 gromos53a6.ff/aminoacids.rtp
    "ASN1",
    "CYS1",
    "HISA",
    "HISB",
    "HIS2",
    # from Gromacs 4.5.3 amber03.ff/aminoacids.rtp
    "HID",
    "HIE",
    "HIP",
    "ORN",
    "DAB",
    "LYN",
    "HYP",
    "CYM",
    "CYX",
    "ASH",
    "GLH",
    "ACE",
    "NME",
    # from Gromacs 2016.3 amber99sb-star-ildn.ff/aminoacids.rtp
    "NALA",
    "NGLY",
    "NSER",
    "NTHR",
    "NLEU",
    "NILE",
    "NVAL",
    "NASN",
    "NGLN",
    "NARG",
    "NHID",
    "NHIE",
    "NHIP",
    "NTRP",
    "NPHE",
    "NTYR",
    "NGLU",
    "NASP",
    "NLYS",
    "NPRO",
    "NCYS",
    "NCYX",
    "NMET",
    "CALA",
    "CGLY",
    "CSER",
    "CTHR",
    "CLEU",
    "CILE",
    "CVAL",
    "CASF",
    "CASN",
    "CGLN",
    "CARG",
    "CHID",
    "CHIE",
    "CHIP",
    "CTRP",
    "CPHE",
    "CTYR",
    "CGLU",
    "CASP",
    "CLYS",
    "CPRO",
    "CCYS",
    "CCYX",
    "CMET",
    "CME",
    "ASF",
}

# A set of nucleic acid residues. Taken from MDAnalysis.
_nucl_res = {
    "ADE",
    "URA",
    "CYT",
    "GUA",
    "THY",
    "DA",
    "DC",
    "DG",
    "DT",
    "RA",
    "RU",
    "RG",
    "RC",
    "A",
    "T",
    "U",
    "C",
    "G",
    "DA5",
    "DC5",
    "DG5",
    "DT5",
    "DA3",
    "DC3",
    "DG3",
    "DT3",
    "RA5",
    "RU5",
    "RG5",
    "RC5",
    "RA3",
    "RU3",
    "RG3",
    "RC3",
}

# A list of ion elements.
_ions = [
    "F",
    "Cl",
    "Br",
    "I",
    "Li",
    "Na",
    "K",
    "Rb",
    "Cs",
    "Mg",
    "Tl",
    "Cu",
    "Ag",
    "Be",
    "Cu",
    "Ni",
    "Pt",
    "Zn",
    "Co",
    "Pd",
    "Ag",
    "Cr",
    "Fe",
    "Mg",
    "V",
    "Mn",
    "Hg",
    "Cd",
    "Yb",
    "Ca",
    "Sn",
    "Pb",
    "Eu",
    "Sr",
    "Sm",
    "Ba",
    "Ra",
    "Al",
    "Fe",
    "Cr",
    "In",
    "Tl",
    "Y",
    "La",
    "Ce",
    "Pr",
    "Nd",
    "Sm",
    "Eu",
    "Gd",
    "Tb",
    "Dy",
    "Er",
    "Tm",
    "Lu",
    "Hf",
    "Zr",
    "Ce",
    "U",
    "Pu",
    "Th",
]
