#!/usr/bin/env bash

# Exit if we are only editing the commit message.
if git diff --cached --quiet ; then
    exit
fi

# If .ciignore doesn't exists, just quit this Git hook.
if [[ ! -a .ciignore ]]; then
	exit
fi

# If the commit message already contains ***NO_CI***, the exit.
if grep -q "***NO_CI***" $1; then
    exit
fi

# Load in every file that will be changed via this commit into an array.
changes=$(git diff --name-only --cached)

git diff --name-only --cached

# Load the patterns we want to skip into an array.
mapfile -t blacklist < .ciignore

for i in "${blacklist[@]}"
do
	# Remove the current pattern from the list of changes.
	changes=( ${changes[@]/$i/} )

	if [[ ${#changes[@]} -eq 0 ]]; then
		# If we've exhausted the list of changes before we've finished going
		# through patterns, that's okay, just quit the loop.
		break
	fi
done

if [[ ${#changes[@]} -gt 0 ]]; then
	# If there's still changes left, then we have stuff to build, leave the commit alone.
	exit
fi

# Delete all comments from commit message.
sed -i.bak -e "/^#/d" "$1" && rm "$1.bak"

# Append "***NO_CI*** to the commit message.
sed -i.bak -e "\$s/$/ ***NO_CI***/" "$1" && rm "$1".bak
